message_client:
  receiver_url: localhost
  topic: camera
  qos: 0
logger:
  level: DEBUG
location:
  latitude: -34.5884843
  longitude: -58.3962122
camera:
  type: VideoCamera
  options:
    resolution: 1920x1080
    framerate: 24
