message_client:
  user: fiubrother
  password: alwayswatching
  connection_url: 192.168.0.19 # ec2-34-222-140-191.us-west-2.compute.amazonaws.com
  topic: camera1
  qos: 0
logger:
  level: WARNING
camera:
  id: 'camera1'
  type: VideoCamera
  options:
    resolution: 1920x1080
    framerate: 24