publisher:
  host: 192.168.1.28
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: video_chunks
camera:
  id: 'CAMERA_1'
  type: rasp_camera
video_recorder:
    resolution: 1280x720
    recording_time: 1
    framerate: 24