publisher:
  username: fiubrother
  password: alwayswatching
  host: 192.168.1.28
  exchange: fiubrother
  queue: video_chunks
camera:
  id: 'CAMERA_1'
  type: rasp_camera
  options:
    resolution: 1920x1080
    recording_time: 1
    framerate: 24