message_client:
  username: fiubrother
  password: alwayswatching
  host: 192.168.0.19 # ec2-34-222-140-191.us-west-2.compute.amazonaws.com
  exchange: fiubrother
  queue: video_chunks
camera:
  id: 'CAMERA_1'
  type: rasp_camera
  options:
    resolution: 1920x1080
    recording_time: 1
    framerate: 24