id: 'camera-1'
publisher:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: video_chunks
video_recorder:
    resolution: 1024x768
    recording_time: 5
    framerate: 30
video_storage:
  host: localhost
  port: 9500
  access_key: fiubrother
  secret_key: alwayswatching
